# Generated by Django 3.2.13 on 2022-05-23 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opencvapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='slider',
            field=models.IntegerField(default=21),
        ),
    ]
